nginx:
  build: ./nginx
  ports:
    - 3000:80
  links:
    - php
  volumes_from:
    - app

php:
  build: ./php/
  expose:
    - 9000
  links:
    - mysql 
  volumes_from:
    - app

app:
  image: php:7.0-fpm
  volumes:
    - ./movies/public:/var/www/html
    - ./movies:/var/www
  command: "true"

mysql:
  image: mysql:latest
  volumes:
    - ./mysql/data/sakila-schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
    - ./mysql/data/sakila-data.sql:/docker-entrypoint-initdb.d/2-data.sql
  command: --default-authentication-plugin=mysql_native_password
  ports: 
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: secret
    MYSQL_DATABASE: sakila
    MYSQL_USER: sakila
    MYSQL_PASSWORD: sakila
  restart: always

